### ISSUE TITLE
Max Entries

### ISSUE THREAD

**Issue by cmay10** [jaebradley/draftkings_client#38]
Is there a way to see the maximum number of entries for each contest? M150, M20, Single Entry, etc.?

**Comment by jaebradley** [comment]
@cmay10 holy cow - sorry that this issue has been open for so long.

I don't know if you ended up finding a solution, or if I'm interpreting your question correctly, but in the `v3` version of this library, there is a `contests` method that returns the list of contests for a given `Sport`.

There is an `entries_details` field in each returned `Contest` object that has a `maximum` field.

This `maximum` field should represent the maximum number of entries for that contest.

Here's an example that shows the maximum entries for an upcoming `NBA` contest:

 ![image](https://user-images.githubusercontent.com/8136030/102574794-a5d40980-40bf-11eb-8721-b4f552d744b1.jpeg)

Here's a screenshot of the contest details on the DraftKings website taken shortly after:

![image](https://user-images.githubusercontent.com/8136030/102574880-dc118900-40bf-11eb-9b69-b6d694f1666d.jpeg)

* Link to `repl.it`: https://repl.it/@jaebradley/Maximum-Contest-Entries#main.py
